# version: '3.8'

# services:
#   weaviate:
#     image: cr.weaviate.io/semitechnologies/weaviate:1.25.9
#     ports:
#       - "8080:8080"
#       - "50051:50051"
#     environment:
#       QUERY_DEFAULTS_LIMIT: 25
#       AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
#       PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
#       DEFAULT_VECTORIZER_MODULE: text2vec-transformers
#       ENABLE_MODULES: text2vec-transformers
#       TRANSFORMERS_INFERENCE_API: 'http://t2v-transformer:8080'
#     volumes:
#       - weaviate_data:/var/lib/weaviate
#     restart: on-failure:0
#     depends_on:
#       - t2v-transformer

#   t2v-transformer:
#     image: semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L6-v2
#     environment:
#       ENABLE_CUDA: '0'

#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     depends_on:
#       - weaviate
#       - t2v-transformer
#     environment:
#       WEAVIATE_URL: "http://weaviate:8080"

# volumes:
#   weaviate_data:


version: '3.8'

services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.9
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - weaviate
    environment:
      WEAVIATE_URL: "http://weaviate:8080"

volumes:
  weaviate_data:




  # postgres:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: mentalhealth
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"





# version: '3.8'

# services:
#   weaviate:
#     image: cr.weaviate.io/semitechnologies/weaviate:1.25.9
#     ports:
#       - "8080:8080"
#       - "50051:50051"
#     environment:
#       QUERY_DEFAULTS_LIMIT: 25
#       AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
#       PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
#       DEFAULT_VECTORIZER_MODULE: text2vec-transformers
#       ENABLE_MODULES: text2vec-transformers
#       TRANSFORMERS_INFERENCE_API: 'http://t2v-transformer:8080'
#     volumes:
#       - weaviate_data:/var/lib/weaviate
#     restart: on-failure:0
#     depends_on:
#       - t2v-transformer

#   t2v-transformer:
#     image: semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L6-v2
#     environment:
#       ENABLE_CUDA: '0'

# volumes:
#   weaviate_data:

