# version: '3.8'

# services:
#   weaviate:
#     image: semitechnologies/weaviate:latest
#     ports:
#       - "8080:8080"
#     environment:
#       QUERY_DEFAULTS_LIMIT: 20
#       AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      
#   app:
#     build: .
#     ports:
#       - "8000:8000"
#     depends_on:
#       - weaviate
#     environment:
#       WEAVIATE_URL: "http://weaviate:8080"
#     volumes:
#       - .:/app
#     command: uvicorn app:app --host 0.0.0.0 --port 8000


version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.24.20
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 10
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
      CLUSTER_HOSTNAME: 'node1'
volumes:
  weaviate_data:
